'use client';

import type { Control, FieldErrors, UseFormRegister } from 'react-hook-form';
import { z } from 'zod';
import { Choice, Field, Input, Select } from '@/components/ui';
import type { Coupon, CouponBody } from '@/lib/types';
import { fromLocalInput, toLocalInput } from './datetime-local';

export const couponSchema = z
  .object({
    // Auto-generated by the server on create (see coupon.service.ts); this
    // field only ever holds an existing coupon's code while editing.
    code: z
      .string()
      .trim()
      .max(40)
      .regex(/^[A-Za-z0-9_-]+$/, 'Letters, digits, - and _ only')
      .or(z.literal('')),
    type: z.enum(['PERCENT', 'AMOUNT']),
    value: z.number({ message: 'Enter a number' }).positive('Must be more than 0'),
    isActive: z.boolean(),
    startsAt: z.string(),
    endsAt: z.string(),
    // Blank = unlimited. NaN comes from an empty <input type=number>.
    maxRedemptions: z.number().int().positive().optional().or(z.nan()),
    maxPerCustomer: z.number().int().positive().optional().or(z.nan()),
  })
  .superRefine((v, ctx) => {
    if (v.type === 'PERCENT' && v.value > 100) {
      ctx.addIssue({ code: 'custom', path: ['value'], message: 'A percentage is 0–100' });
    }
    if (v.startsAt && v.endsAt && new Date(v.endsAt) <= new Date(v.startsAt)) {
      ctx.addIssue({ code: 'custom', path: ['endsAt'], message: 'Must be after the start' });
    }
  });
export type CouponFormValues = z.infer<typeof couponSchema>;

export const blankCouponValues: CouponFormValues = {
  code: '',
  type: 'PERCENT',
  value: 10,
  isActive: true,
  startsAt: '',
  endsAt: '',
  maxRedemptions: undefined,
  // Single-use per customer by default — clear it for a multi-use / unlimited code.
  maxPerCustomer: 1,
};

export function couponValuesFromExisting(c: Coupon): CouponFormValues {
  return {
    code: c.code,
    type: c.type,
    value: Number(c.value),
    isActive: c.isActive,
    startsAt: toLocalInput(c.startsAt),
    endsAt: toLocalInput(c.endsAt),
    maxRedemptions: c.maxRedemptions ?? undefined,
    maxPerCustomer: c.maxPerCustomer ?? undefined,
  };
}

export function couponBodyFromValues(form: CouponFormValues, isEditing: boolean): CouponBody {
  return {
    // Omitted on create so the server auto-generates a unique code.
    ...(isEditing ? { code: form.code } : {}),
    type: form.type,
    value: form.value,
    isActive: form.isActive,
    startsAt: fromLocalInput(form.startsAt),
    endsAt: fromLocalInput(form.endsAt),
    maxRedemptions: Number.isFinite(form.maxRedemptions) ? form.maxRedemptions : null,
    maxPerCustomer: Number.isFinite(form.maxPerCustomer) ? form.maxPerCustomer : null,
  };
}

export function CouponFormFields<T extends CouponFormValues>({
  register,
  errors,
  busy,
  locale,
  isEditing,
}: {
  register: UseFormRegister<T>;
  errors: FieldErrors<T>;
  busy: boolean;
  locale: 'en' | 'ar';
  isEditing: boolean;
}) {
  const isAr = locale === 'ar';
  const t = (en: string, ar: string) => (isAr ? ar : en);

  return (
    <>
      {isEditing ? (
        <div className="admin-form__row">
          <Field label={t('Code', 'الرمز')} hint={t('Auto-generated; stored upper-cased', 'يُنشأ تلقائيًا؛ يُخزَّن بأحرف كبيرة')}>
            {(p) => <Input {...p} {...register('code' as never)} disabled />}
          </Field>
        </div>
      ) : (
        <p className="admin-form__hint">
          {t(
            'A unique 12-digit code (e.g. 4821-0937-6650) will be generated automatically.',
            'سيتم إنشاء رمز فريد مكوّن من 12 رقمًا (مثل 4821-0937-6650) تلقائيًا.'
          )}
        </p>
      )}

      <div className="admin-form__row">
        <Field label={t('Type', 'النوع')}>
          {(p) => (
            <Select {...p} {...register('type' as never)} disabled={busy}>
              <option value="PERCENT">{t('Percentage off', 'نسبة مئوية')}</option>
              <option value="AMOUNT">{t('Amount off ($)', 'مبلغ ثابت ($)')}</option>
            </Select>
          )}
        </Field>
        <Field label={t('Value', 'القيمة')} error={errors.value?.message as string | undefined}>
          {(p) => (
            <Input {...p} type="number" min={0} step="0.01" {...register('value' as never, { valueAsNumber: true })} disabled={busy} />
          )}
        </Field>
      </div>

      <div className="admin-form__row">
        <Field label={t('Starts', 'يبدأ')} hint={t('Blank = now', 'فارغ = الآن')} error={errors.startsAt?.message as string | undefined}>
          {(p) => <Input {...p} type="datetime-local" {...register('startsAt' as never)} disabled={busy} />}
        </Field>
        <Field label={t('Ends', 'ينتهي')} hint={t('Blank = no end', 'فارغ = بلا نهاية')} error={errors.endsAt?.message as string | undefined}>
          {(p) => <Input {...p} type="datetime-local" {...register('endsAt' as never)} disabled={busy} />}
        </Field>
      </div>

      <div className="admin-form__row">
        <Field
          label={t('Total uses', 'إجمالي مرات الاستخدام')}
          hint={t('Blank = unlimited', 'فارغ = بلا حد')}
          error={errors.maxRedemptions?.message as string | undefined}
        >
          {(p) => (
            <Input {...p} type="number" min={1} step="1" {...register('maxRedemptions' as never, { valueAsNumber: true })} disabled={busy} />
          )}
        </Field>
        <Field
          label={t('Uses per customer', 'مرات لكل عميل')}
          hint={t('Blank = unlimited', 'فارغ = بلا حد')}
          error={errors.maxPerCustomer?.message as string | undefined}
        >
          {(p) => (
            <Input {...p} type="number" min={1} step="1" {...register('maxPerCustomer' as never, { valueAsNumber: true })} disabled={busy} />
          )}
        </Field>
      </div>

      <Choice type="checkbox" label={t('Active', 'مُفعَّل')} {...register('isActive' as never)} disabled={busy} />
    </>
  );
}
